services:
  backend:
    build: ./backend
    container_name: medical-backend
    ports:
      - "8000:8000"
    volumes:
      - uploads_data:/app/uploads
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: medical-frontend
    ports:
      - "6363:80"
    depends_on:
      - backend
    env_file:
      - .env
    restart: unless-stopped

volumes:
  uploads_data: